project_id = "ptiwdwfdckfqivoocyvp"

[functions.notify-appointment]
verify_jwt = false

[functions.send-appointment-confirmation]
verify_jwt = false

[functions.bb-lookup]
verify_jwt = false

[functions.send-reschedule-notification]
verify_jwt = false

[functions.analyze-vehicle-damage]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true